#!/bin/bash

RELEASE=${1:-18}
BUILD_NAME=${2:-fedora-${RELEASE}-x86_64}

BIN_DIR=$(cd $(dirname "$0") && pwd)

sudo virt-install \
    --name $BUILD_NAME \
    --ram 1024 \
    --cpu host \
    --vcpus 1 \
    --nographics \
    --os-type=linux \
    --os-variant=fedora18 \
    --location=http://mirrors.kernel.org/fedora/releases/18/Fedora/x86_64/os/ \
    --initrd-inject=$BIN_DIR/$BUILD_NAME.ks \
    --extra-args="ks=file:/$BUILD_NAME.ks text console=tty0 utf8 console=ttyS0,115200" \
    --disk path=/var/lib/libvirt/images/$BUILD_NAME.img,size=2,bus=virtio \
    --force \
    --noreboot

#    --location=http://mirrors.kernel.org/centos/6/os/x86_64 \

sudo virt-sysprep --no-selinux-relabel -a /var/lib/libvirt/images/$BUILD_NAME.img

sudo virt-sparsify --convert qcow2 --compress /var/lib/libvirt/images/$BUILD_NAME.img $BUILD_NAME.qcow2

